import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;



import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectDir = path.dirname(fileURLToPath(import.meta.url));

const vaultPath = process.env.OBSIDIAN_VAULT;
const pluginId = "my-plugin";

if (!vaultPath) {
    throw new Error("OBSIDIAN_VAULT is not set");
}

const pluginDir = path.join(
    vaultPath
);

const copyAssets = {
    name: "copy-assets",

    setup(build) {
        build.onEnd((result) => {
            if (result.errors.length > 0) return;

            const source = path.join(
                projectDir,
                "gardenOfGrowth.json"
            );

            const destination = path.join(
                pluginDir,
                "gardenOfGrowth.json"
            );

            fs.mkdirSync(path.dirname(destination), {
                recursive: true,
            });

            fs.copyFileSync(source, destination);
        });
    },
};



const prod = (process.argv[2] === "production");

await esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    watch: !prod,
    plugins: [copyAssets]

}).catch(() => process.exit(1));