"use strict";
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  ExampleModal: () => ExampleModal,
  SQUARE_VIEW: () => SQUARE_VIEW,
  SquareView: () => SquareView,
  VIEW_TYPE_EXAMPLE: () => VIEW_TYPE_EXAMPLE,
  default: () => ExamplePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var cards = /* @__PURE__ */ new Map();
var VIEW_TYPE_EXAMPLE = "example-view";
var SQUARE_VIEW = "square_view";
var ExamplePlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("GardenOfGrowth loading...");
    await this.loadSettings();
    this.registerView(
      SQUARE_VIEW,
      (leaf) => new SquareView(leaf, this)
    );
    this.addRibbonIcon("sun-snow", "GardenOfGrowth", () => {
      console.log("addRibbonIcon, you!");
      this.activateView();
    });
    this.addCommand({
      id: "checkLineForDoubleColon",
      name: "Check line for :: item",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const lineText = editor.getLine(cursor.line);
        if (lineText.includes("::")) {
          let cardID = this.generateId();
          let splitText = lineText.split("::");
          let front = splitText[0];
          let back = splitText[1];
          console.log("lineText splitText, Front, back", lineText, splitText, front, back);
          cards.set(front + back, {
            id: cardID,
            name: front,
            front,
            back,
            state: 0,
            repetitionCount: 0,
            interval: 1,
            easinessFactor: 2.5,
            reviewedAt: null,
            dueDate: new Date(Date.now() + 24 * 60 * 60 * 1e3)
          });
          this.saveSettings();
          const leaves = this.app.workspace.getLeavesOfType(SQUARE_VIEW);
          for (const leaf of leaves) {
            leaf.rebuildView();
          }
        } else {
          console.log("No :: found on this line");
        }
      }
    });
  }
  onunload() {
    this.statusBarElement.remove();
  }
  generateId(length = 8) {
    const characters = "0123456789";
    let result = "";
    for (let i = 0; i < length; i++) {
      const randomIndex = Math.floor(Math.random() * characters.length);
      result += characters[randomIndex];
    }
    return result;
  }
  async saveSettings() {
    try {
      await this.app.vault.adapter.write(
        "cards.json",
        JSON.stringify(cards, null, 2)
      );
      console.log("Write done", this.app.vault.adapter.getName());
    } catch (e) {
      console.log(e);
    }
  }
  async loadSettings() {
    try {
      if (await this.app.vault.adapter.exists("cards.json")) {
        const fileContent = await this.app.vault.adapter.read("cards.json");
        const data = JSON.parse(fileContent);
        data.length = 0;
        cardList.push(...data);
        console.log("Loaded cards:", cardList);
        for (const card of cardList) {
          cards.set(card.id, card);
        }
      }
    } catch (error) {
      console.error("Could not load cards.json:", error);
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(SQUARE_VIEW);
    if (leaves.length > 0) {
      leaf = leaves[0];
      console.log("HTML");
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: SQUARE_VIEW,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  sm2(card, quality) {
    if (quality < 3) {
      card.repetitionCount = 0;
      card.interval = 1;
    } else {
      if (card.repetitionCount === 0) {
        card.interval = 1;
        card.state = 1;
      } else if (card.repetitionCount === 1) {
        card.interval = 6;
      } else {
        card.interval = Math.round(card.interval * card.easinessFactor);
      }
      card.repetitionCount += 1;
    }
    card.easinessFactor = card.easinessFactor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
    if (card.easinessFactor < 1.3) {
      card.easinessFactor = 1.3;
    }
    if (card.easinessFactor > 3.5) {
      card.state = 3;
    }
    card.reviewedAt = new Date();
    const dueDate = new Date(card.reviewedAt);
    dueDate.setDate(dueDate.getDate() + card.interval);
    card.dueDate = dueDate;
    const now = new Date();
    if (card.dueDate.getTime() <= now.getTime()) {
      card.state = 4;
    }
    return card;
  }
};
var SquareView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return SQUARE_VIEW;
  }
  getDisplayText() {
    return "Square view";
  }
  async onOpen() {
    console.log("HTML");
    const container = this.contentEl;
    container.empty();
    const stateCards = /* @__PURE__ */ new Map();
    for (const cardName of cards.keys()) {
      const card = cards.get(cardName);
      const cardsInState = stateCards.get(card.state) ?? [];
      cardsInState.push(card.id);
      stateCards.set(card.state, cardsInState);
    }
    container.createEl("h2", { text: "Garden Of Growth" });
    const header = ["Seed \u{1F331}", "Pulp \u{1F33F}", "Flower \u{1F339}", "Wilt \u{1F940}"];
    const color = ["#2d6a4f", "#ed98cdff", "#bbdc50ff", "#9b0cdeff"];
    for (const state of stateCards.keys()) {
      const cardsInState = stateCards.get(state);
      const section = container.createEl("section");
      section.style.backgroundColor = color[state];
      section.style.color = "white";
      section.style.padding = "16px";
      section.style.borderRadius = "8px";
      section.style.margin = "12px";
      section.createEl("h2", { text: header[state] });
      for (const id of stateCards.get(state)) {
        const reviewButton = section.createEl("button", { text: cards.get(id)?.front });
        reviewButton.style.padding = "16px";
        reviewButton.style.borderRadius = "8px";
        reviewButton.style.margin = "12px";
        reviewButton.addEventListener("click", async () => {
          console.log(`Reviewing ${id}`);
          new ExampleModal(this.app, this.plugin, cards.get(id), (result) => {
            new import_obsidian.Notice(`Hello, ${cards.get(id).back}!`);
            this.onOpen();
          }).open();
        });
        console.log("Add button");
      }
    }
  }
  async onClose() {
  }
};
var ExampleModal = class extends import_obsidian.Modal {
  constructor(app, plugin, card, onSubmit) {
    super(app);
    let icons = ["", "\u{1F331}", "\u{1F33F}", "\u{1F339}", "\u{1F940}"];
    this.setTitle(icons[card.state]);
    new import_obsidian.Setting(this.contentEl).setName("Flash Card Front " + card.front);
    const backText = this.contentEl.createEl("p", {
      text: "Flash Card Back " + card.back
    });
    backText.style.display = "none";
    let secondButtonsCreated = false;
    const backSetting = new import_obsidian.Setting(this.contentEl);
    backSetting.addButton(
      (back) => back.setButtonText("Show Back").onClick(() => {
        backText.style.display = "block";
        backSetting.settingEl.remove();
        if (!secondButtonsCreated) {
          secondButtonsCreated = true;
          new import_obsidian.Setting(this.contentEl).addButton(
            (Poor) => Poor.setButtonText("1 Poor").onClick(() => {
              console.log("1 clicked");
              plugin.sm2(card, 1);
              plugin.saveSettings();
              console.log("CARD UPDATE: ", card);
              this.close();
            })
          ).addButton(
            (Fair) => Fair.setButtonText("2 Fair").onClick(() => {
              console.log("2 clicked");
              plugin.sm2(card, 2);
              plugin.saveSettings();
              console.log("CARD UPDATE: ", card);
              this.close();
            })
          ).addButton(
            (Average) => Average.setButtonText("3 Average").onClick(() => {
              console.log("3 clicked");
              plugin.sm2(card, 3);
              plugin.saveSettings();
              console.log("CARD UPDATE: ", card);
              this.close();
            })
          ).addButton(
            (Good) => Good.setButtonText("4 Good").onClick(() => {
              console.log("4 clicked");
              plugin.sm2(card, 4);
              plugin.saveSettings();
              console.log("CARD UPDATE: ", card);
              this.close();
            })
          ).addButton(
            (Excellent) => Excellent.setButtonText("5 Excellent").onClick(() => {
              console.log("3 clicked");
              plugin.sm2(card, 5);
              plugin.saveSettings();
              const leaves = this.app.workspace.getLeavesOfType(SQUARE_VIEW);
              for (const leaf of leaves) {
                leaf.rebuildView();
              }
              console.log("CARD UPDATE: ", card);
              this.close();
            })
          );
        }
      })
    );
  }
};
